### PR TITLE
Fix SFOS v2.1.0.9: fix ambiguous index variable

### PR DESCRIPTION
**Pull request by Tofee**
Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>

### CODE REVIEW

**Comment by pimpreneil** [comment]
Thanks @Tofee for fixing that.
To celebrate, I am doing a PR with 4 new puzzles 🍾

**Comment by erikderzweite** [comment]
Is there any reason you choose to use

`Levels.arrayToList(myDiff, levelList)` instead of 
`Levels.arrayToList(model.index, levelList)` ? I'm new to SF development so I'm curious about stuff.

**Comment by Tofee** [comment]
@erikderzweite There is one technical reason: if you have embedded delegates in the same file, the variable you reference becomes unclear.
But the main reason here was that "myDiff" was tested in the line before, and that "myDiff" ("my difficulty") has more meaning then "model.index", which is generic. So it's easier to understand the code.

**Comment by zarelit** [comment]
This patch is really ready for release, maybe we should ping @Baspar  ? :smiley:

**Comment by Baspar** [comment]
Ouch so sorry for the delay :'(
I'm not on sailfish anymore sadly, I left the boat :(

I'll accept this PR, but if someone wants to continue this project, the best solution might be to fork this repo

**Comment by direc85** [comment]
Oh, I just now read your previous comment. I just pushed my updated fork to Harbour QA. It's simply called Picross 2.

**Pull request merged**
